ARG FROM_DIGEST
FROM localagi/fastchat-controller@${FROM_DIGEST}

EXPOSE $FASTCHAT_API_PORT

ENTRYPOINT python3 -m fastchat.serve.openai_api_server
CMD ["--host","$FASTCHAT_API_HOST","--port","$FASTCHAT_API_PORT","--controller-address","$FASTCHAT_CONTROLLER_ADDRESS"]
